package com.zlebank.zplatform.trade.model;

// Generated 2016-8-8 16:38:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONCreator;
import com.alibaba.fastjson.annotation.JSONField;

/**
 * TTxnsWechatOrderinfo generated by hbm2java
 */
@Entity
@Table(name = "T_TXNS_WECHAT_ORDERINFO")
public class PojoTxnsWechatOrderinfo implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -7256242183785459987L;
	@JSONField(serialize=false)
	private long tid;
	@JSONField(name="appid")
	private String appid;
	@JSONField(name="mch_id")
	private String mchId;
	@JSONField(name="device_info")
	private String deviceInfo;
	@JSONField(name="body")
	private String body;
	@JSONField(name="detail")
	private String detail;
	@JSONField(name="attach")
	private String attach;
	@JSONField(name="out_trade_no")
	private String outTradeNo;
	@JSONField(name="fee_type")
	private String feeType;
	@JSONField(name="total_fee")
	private Long totalFee;
	@JSONField(name="spbill_create_ip")
	private String spbillCreateIp;
	@JSONField(name="time_start")
	private String timeStart;
	@JSONField(name="time_expire")
	private String timeExpire;
	@JSONField(name="goods_tag")
	private String goodsTag;
	@JSONField(name="notify_url")
	private String notifyUrl;
	@JSONField(name="trade_type")
	private String tradeType;
	@JSONField(name="product_id")
	private String productId;
	@JSONField(name="imit_pay")
	private String imitPay;
	@JSONField(name="openid")
	private String openid;
	@JSONField(serialize=false)
	private String status;
	@JSONField(name="code_url")
	private String codeUrl;
	@JSONField(name="prepay_id")
	private String prepayId;
	@JSONField(serialize=false)
	private String txnseqno;

	public PojoTxnsWechatOrderinfo() {
	}

	public PojoTxnsWechatOrderinfo(long tid) {
		this.tid = tid;
	}

	public PojoTxnsWechatOrderinfo(long tid, String appid, String mchId,
			String deviceInfo, String body, String detail, String attach,
			String outTradeNo, String feeType, Long totalFee,
			String spbillCreateIp, String timeStart, String timeExpire,
			String goodsTag, String notifyUrl, String tradeType,
			String productId, String imitPay, String openid, String status) {
		this.tid = tid;
		this.appid = appid;
		this.mchId = mchId;
		this.deviceInfo = deviceInfo;
		this.body = body;
		this.detail = detail;
		this.attach = attach;
		this.outTradeNo = outTradeNo;
		this.feeType = feeType;
		this.totalFee = totalFee;
		this.spbillCreateIp = spbillCreateIp;
		this.timeStart = timeStart;
		this.timeExpire = timeExpire;
		this.goodsTag = goodsTag;
		this.notifyUrl = notifyUrl;
		this.tradeType = tradeType;
		this.productId = productId;
		this.imitPay = imitPay;
		this.openid = openid;
		this.status = status;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "APPID", length = 32)
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "MCH_ID", length = 32)
	public String getMchId() {
		return this.mchId;
	}

	public void setMchId(String mchId) {
		this.mchId = mchId;
	}

	@Column(name = "DEVICE_INFO", length = 32)
	public String getDeviceInfo() {
		return this.deviceInfo;
	}

	public void setDeviceInfo(String deviceInfo) {
		this.deviceInfo = deviceInfo;
	}

	@Column(name = "BODY", length = 256)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "DETAIL", length = 1024)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "ATTACH", length = 128)
	public String getAttach() {
		return this.attach;
	}

	public void setAttach(String attach) {
		this.attach = attach;
	}

	@Column(name = "OUT_TRADE_NO", length = 32)
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	@Column(name = "FEE_TYPE", length = 16)
	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	@Column(name = "TOTAL_FEE", precision = 12, scale = 0)
	public Long getTotalFee() {
		return this.totalFee;
	}

	public void setTotalFee(Long totalFee) {
		this.totalFee = totalFee;
	}

	@Column(name = "SPBILL_CREATE_IP", length = 16)
	public String getSpbillCreateIp() {
		return this.spbillCreateIp;
	}

	public void setSpbillCreateIp(String spbillCreateIp) {
		this.spbillCreateIp = spbillCreateIp;
	}

	@Column(name = "TIME_START", length = 14)
	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	@Column(name = "TIME_EXPIRE", length = 14)
	public String getTimeExpire() {
		return this.timeExpire;
	}

	public void setTimeExpire(String timeExpire) {
		this.timeExpire = timeExpire;
	}

	@Column(name = "GOODS_TAG", length = 32)
	public String getGoodsTag() {
		return this.goodsTag;
	}

	public void setGoodsTag(String goodsTag) {
		this.goodsTag = goodsTag;
	}

	@Column(name = "NOTIFY_URL", length = 256)
	public String getNotifyUrl() {
		return this.notifyUrl;
	}

	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}

	@Column(name = "TRADE_TYPE", length = 16)
	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	@Column(name = "PRODUCT_ID", length = 32)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "IMIT_PAY", length = 32)
	public String getImitPay() {
		return this.imitPay;
	}

	public void setImitPay(String imitPay) {
		this.imitPay = imitPay;
	}

	@Column(name = "OPENID", length = 128)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the codeUrl
	 */
	@Column(name = "CODE_URL")
	public String getCodeUrl() {
		return codeUrl;
	}

	/**
	 * @param codeUrl the codeUrl to set
	 */
	public void setCodeUrl(String codeUrl) {
		this.codeUrl = codeUrl;
	}

	/**
	 * @return the prepayId
	 */
	@Column(name = "PREPAY_ID")
	public String getPrepayId() {
		return prepayId;
	}

	/**
	 * @param prepayId the prepayId to set
	 */
	public void setPrepayId(String prepayId) {
		this.prepayId = prepayId;
	}

	/**
	 * @return the txnseqno
	 */
	@Column(name = "TXNSEQNO")
	public String getTxnseqno() {
		return txnseqno;
	}

	/**
	 * @param txnseqno the txnseqno to set
	 */
	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	
}
