package com.zlebank.zplatform.trade.model;

// Generated 2016-8-24 9:51:54 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TTxnsCharge generated by hbm2java
 */
@Entity
@Table(name = "T_TXNS_CHARGE", uniqueConstraints = @UniqueConstraint(columnNames = "CHARGENO"))
public class PojoTxnsCharge implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 7532263517672128799L;
	private long id;
	private String chargeno;
	private String memberid;
	private String chargetype;
	private long amount;
	private String status;
	private String chargenoinstid;
	private long inuser;
	private Date intime;
	private Long stexauser;
	private Date stexatime;
	private String stexaopt;
	private Long cvlexauser;
	private Date cvlexatime;
	private String cvlexaopt;
	private String notes;
	private String remarks;
	private String chargecode;
	private String tn;
	
	
	public PojoTxnsCharge() {
	}

	public PojoTxnsCharge(long id, String chargeno, String memberid,
			String chargetype, long amount, String status,
			String chargenoinstid, long inuser, Date intime) {
		this.id = id;
		this.chargeno = chargeno;
		this.memberid = memberid;
		this.chargetype = chargetype;
		this.amount = amount;
		this.status = status;
		this.chargenoinstid = chargenoinstid;
		this.inuser = inuser;
		this.intime = intime;
	}

	public PojoTxnsCharge(long id, String chargeno, String memberid,
			String chargetype, long amount, String status,
			String chargenoinstid, long inuser, Date intime, Long stexauser,
			Date stexatime, String stexaopt, Long cvlexauser, Date cvlexatime,
			String cvlexaopt, String notes, String remarks, String chargecode) {
		this.id = id;
		this.chargeno = chargeno;
		this.memberid = memberid;
		this.chargetype = chargetype;
		this.amount = amount;
		this.status = status;
		this.chargenoinstid = chargenoinstid;
		this.inuser = inuser;
		this.intime = intime;
		this.stexauser = stexauser;
		this.stexatime = stexatime;
		this.stexaopt = stexaopt;
		this.cvlexauser = cvlexauser;
		this.cvlexatime = cvlexatime;
		this.cvlexaopt = cvlexaopt;
		this.notes = notes;
		this.remarks = remarks;
		this.chargecode = chargecode;
	}

	@Id
    @GeneratedValue(generator = "id_gen")
    @GenericGenerator(name = "id_gen", strategy = "enhanced-table", parameters = {
            @Parameter(name = "table_name", value = "T_C_PRIMAY_KEY"),
            @Parameter(name = "value_column_name", value = "NEXT_ID"),
            @Parameter(name = "segment_column_name", value = "KEY_NAME"),
            @Parameter(name = "segment_value", value = "T_TXNS_CHARGE_ID"),
            @Parameter(name = "increment_size", value = "1"),
            @Parameter(name = "optimizer", value = "pooled-lo") })
	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CHARGENO", unique = true, nullable = false, length = 32)
	public String getChargeno() {
		return this.chargeno;
	}

	public void setChargeno(String chargeno) {
		this.chargeno = chargeno;
	}

	@Column(name = "MEMBERID", nullable = false, length = 15)
	public String getMemberid() {
		return this.memberid;
	}

	public void setMemberid(String memberid) {
		this.memberid = memberid;
	}

	@Column(name = "CHARGETYPE", nullable = false, length = 2)
	public String getChargetype() {
		return this.chargetype;
	}

	public void setChargetype(String chargetype) {
		this.chargetype = chargetype;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 12, scale = 0)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CHARGENOINSTID", nullable = false, length = 8)
	public String getChargenoinstid() {
		return this.chargenoinstid;
	}

	public void setChargenoinstid(String chargenoinstid) {
		this.chargenoinstid = chargenoinstid;
	}

	@Column(name = "INUSER", nullable = false, precision = 10, scale = 0)
	public long getInuser() {
		return this.inuser;
	}

	public void setInuser(long inuser) {
		this.inuser = inuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INTIME", nullable = false, length = 7)
	public Date getIntime() {
		return this.intime;
	}

	public void setIntime(Date intime) {
		this.intime = intime;
	}

	@Column(name = "STEXAUSER", precision = 10, scale = 0)
	public Long getStexauser() {
		return this.stexauser;
	}

	public void setStexauser(Long stexauser) {
		this.stexauser = stexauser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STEXATIME", length = 7)
	public Date getStexatime() {
		return this.stexatime;
	}

	public void setStexatime(Date stexatime) {
		this.stexatime = stexatime;
	}

	@Column(name = "STEXAOPT", length = 256)
	public String getStexaopt() {
		return this.stexaopt;
	}

	public void setStexaopt(String stexaopt) {
		this.stexaopt = stexaopt;
	}

	@Column(name = "CVLEXAUSER", precision = 10, scale = 0)
	public Long getCvlexauser() {
		return this.cvlexauser;
	}

	public void setCvlexauser(Long cvlexauser) {
		this.cvlexauser = cvlexauser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CVLEXATIME", length = 7)
	public Date getCvlexatime() {
		return this.cvlexatime;
	}

	public void setCvlexatime(Date cvlexatime) {
		this.cvlexatime = cvlexatime;
	}

	@Column(name = "CVLEXAOPT", length = 256)
	public String getCvlexaopt() {
		return this.cvlexaopt;
	}

	public void setCvlexaopt(String cvlexaopt) {
		this.cvlexaopt = cvlexaopt;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "CHARGECODE", length = 32)
	public String getChargecode() {
		return this.chargecode;
	}

	public void setChargecode(String chargecode) {
		this.chargecode = chargecode;
	}

	/**
	 * @return the tn
	 */
	@Column(name = "TN")
	public String getTn() {
		return tn;
	}

	/**
	 * @param tn the tn to set
	 */
	public void setTn(String tn) {
		this.tn = tn;
	}

}
