package com.zlebank.zplatform.trade.model;
// default package
// Generated 2016-3-14 18:23:59 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTxnsInsteadPay generated by hbm2java
 */
@Entity
@Table(name = "T_TXNS_INSTEAD_PAY")
public class PojoTxnsInsteadPay implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -4867441730131379452L;
	private long tid;
	private String insteadPayNo;
	private String channelCode;
	private String transferType;
	private String reqFile;
	private String resFile;
	private Date startDate;
	private Date endDate;
	private String status;
	private String remarks;

	public PojoTxnsInsteadPay() {
	}

	public PojoTxnsInsteadPay(long tid) {
		this.tid = tid;
	}

	public PojoTxnsInsteadPay(long tid, String insteadPayNo, String channelCode,
			String transferType, String reqFile, String resFile,
			Date startDate, Date endDate, String status, String remarks) {
		this.tid = tid;
		this.insteadPayNo = insteadPayNo;
		this.channelCode = channelCode;
		this.transferType = transferType;
		this.reqFile = reqFile;
		this.resFile = resFile;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.remarks = remarks;
	}
	
	
	public PojoTxnsInsteadPay( String insteadPayNo, String channelCode,
			String transferType, String reqFile, String resFile,
			Date startDate, Date endDate, String status, String remarks) {
		this.insteadPayNo = insteadPayNo;
		this.channelCode = channelCode;
		this.transferType = transferType;
		this.reqFile = reqFile;
		this.resFile = resFile;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_insteadpay_id") 
    @SequenceGenerator(name="seq_insteadpay_id",sequenceName="SEQ_TXNS_INSTEAD_PAY",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "INSTEAD_PAY_NO", length = 32)
	public String getInsteadPayNo() {
		return this.insteadPayNo;
	}

	public void setInsteadPayNo(String insteadPayNo) {
		this.insteadPayNo = insteadPayNo;
	}

	@Column(name = "CHANNEL_CODE", length = 8)
	public String getChannelCode() {
		return this.channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	@Column(name = "TRANSFER_TYPE", length = 2)
	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	@Column(name = "REQ_FILE", length = 64)
	public String getReqFile() {
		return this.reqFile;
	}

	public void setReqFile(String reqFile) {
		this.reqFile = reqFile;
	}

	@Column(name = "RES_FILE", length = 64)
	public String getResFile() {
		return this.resFile;
	}

	public void setResFile(String resFile) {
		this.resFile = resFile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
