package com.zlebank.zplatform.trade.model;
// default package
// Generated 2015-12-1 14:50:13 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TTransferData generated by hbm2java
 */
@Entity
@Table(name = "T_TRANSFER_DATA")
public class PojoTransferData implements java.io.Serializable {
    private String bankTranDataNo;
    /**
	 * 
	 */
	private static final long serialVersionUID = -2108028525270412164L;
	private long tid;
    private String batchno;
    private String tranid;
    private String acctype;
    private String accno;
    private String accname;
    private String banktype;
    private String bankname;
    private Long transamt;
    private String remark;
    private String resv;
    private String status;
    private String banktranid;
    private String resptype;
    private String respcode;
    private String respmsg;
    private String trandate;
    private String trantime;
    private String relatedorderno;
    private String busicode;
    private String splitflag;
    private String accstatus;
    private String accinfo;
    private String memberid;
    private String busitype;
    private String transfertype;
    /** 创建时间 **/
    private Date createtime;
    /** 初审人 **/
    private Long stexauser;
    /** 初审时间 **/
    private Date stexatime;
    /** 初审意见 **/
    private String stexaopt;
    /** 复审人 **/
    private Long cvlexauser;
    /** 复审时间 **/
    private Date cvlexatime;
    /** 复审意见 **/
    private String cvlexaopt;
    /**手续费**/
    private BigDecimal txnfee;
    /**交易序列号**/
    private String txnseqno;
    /**关联批次号**/
    private String associatedBatch;
    

  
    
    
    
    @Column(name = "ASSOCIATED_BATCH")
    public String getAssociatedBatch() {
        return associatedBatch;
    }
    public void setAssociatedBatch(String associatedBatch) {
        this.associatedBatch = associatedBatch;
    }
    @Column(name = "STEXAUSER")
    public Long getStexauser() {
        return stexauser;
    }
    public void setStexauser(Long stexauser) {
        this.stexauser = stexauser;
    }
    @Column(name = "STEXATIME")
    public Date getStexatime() {
        return stexatime;
    }
    public void setStexatime(Date stexatime) {
        this.stexatime = stexatime;
    }
    @Column(name = "STEXAOPT")
    public String getStexaopt() {
        return stexaopt;
    }
    public void setStexaopt(String stexaopt) {
        this.stexaopt = stexaopt;
    }
    @Column(name = "CVLEXAUSER")
    public Long getCvlexauser() {
        return cvlexauser;
    }
    public void setCvlexauser(Long cvlexauser) {
        this.cvlexauser = cvlexauser;
    }
    @Column(name = "CVLEXATIME")
    public Date getCvlexatime() {
        return cvlexatime;
    }
    public void setCvlexatime(Date cvlexatime) {
        this.cvlexatime = cvlexatime;
    }
    @Column(name = "CVLEXAOPT")
    public String getCvlexaopt() {
        return cvlexaopt;
    }
    public void setCvlexaopt(String cvlexaopt) {
        this.cvlexaopt = cvlexaopt;
    }

    public PojoTransferData() {
    }

    public PojoTransferData(long tid) {
        this.tid = tid;
    }

    public PojoTransferData(long tid, String batchno, String tranid,
            String acctype, String accno, String accname, String banktype,
            String bankname, Long transamt, String remark, String resv,
            String status, String banktranid, String resptype, String respcode,
            String respmsg, String trandate, String trantime,
            String relatedorderno, String busicode) {
        super();
        this.tid = tid;
        this.batchno = batchno;
        this.tranid = tranid;
        this.acctype = acctype;
        this.accno = accno;
        this.accname = accname;
        this.banktype = banktype;
        this.bankname = bankname;
        this.transamt = transamt;
        this.remark = remark;
        this.resv = resv;
        this.status = status;
        this.banktranid = banktranid;
        this.resptype = resptype;
        this.respcode = respcode;
        this.respmsg = respmsg;
        this.trandate = trandate;
        this.trantime = trantime;
        this.relatedorderno = relatedorderno;
        this.busicode = busicode;
    }

    public PojoTransferData(String[] body) {
        super();
        this.tranid = body[0];
        this.banktranid = body[1];
        this.accno = body[2];
        this.accname = body[3];
        this.transamt = Long.valueOf(body[4]);
        this.resptype = body[5];
        this.respcode = body[6];
        this.respmsg = body[7];
        this.trandate = body[8];
        this.trantime = body[9];

    }

    @GenericGenerator(name = "id_gen", strategy = "enhanced-table", parameters = {
            @Parameter(name = "table_name", value = "T_C_PRIMAY_KEY"),
            @Parameter(name = "value_column_name", value = "NEXT_ID"),
            @Parameter(name = "segment_column_name", value = "KEY_NAME"),
            @Parameter(name = "segment_value", value = "T_TRANSFER_BATCH_ID"),
            @Parameter(name = "increment_size", value = "1"),
            @Parameter(name = "optimizer", value = "pooled-lo")})
    @Id
    @GeneratedValue(generator = "id_gen")
    @Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
    public long getTid() {
        return this.tid;
    }

    public void setTid(long tid) {
        this.tid = tid;
    }

    @Column(name = "BATCHNO", length = 8)
    public String getBatchno() {
        return this.batchno;
    }

    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    @Column(name = "TRANID", length = 16)
    public String getTranid() {
        return this.tranid;
    }

    public void setTranid(String tranid) {
        this.tranid = tranid;
    }

    @Column(name = "ACCTYPE", length = 1)
    public String getAcctype() {
        return this.acctype;
    }

    public void setAcctype(String acctype) {
        this.acctype = acctype;
    }

    @Column(name = "ACCNO", length = 64)
    public String getAccno() {
        return this.accno;
    }

    public void setAccno(String accno) {
        this.accno = accno;
    }

    @Column(name = "ACCNAME", length = 512)
    public String getAccname() {
        return this.accname;
    }

    public void setAccname(String accname) {
        this.accname = accname;
    }

    @Column(name = "BANKTYPE", length = 12)
    public String getBanktype() {
        return this.banktype;
    }

    public void setBanktype(String banktype) {
        this.banktype = banktype;
    }

    @Column(name = "BANKNAME", length = 512)
    public String getBankname() {
        return this.bankname;
    }

    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    @Column(name = "TRANSAMT", precision = 12, scale = 0)
    public Long getTransamt() {
        return this.transamt;
    }

    public void setTransamt(Long transamt) {
        this.transamt = transamt;
    }

    @Column(name = "REMARK", length = 512)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "RESV", length = 512)
    public String getResv() {
        return this.resv;
    }

    public void setResv(String resv) {
        this.resv = resv;
    }

    @Column(name = "STATUS", length = 2)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "BANKTRANID", length = 16)
    public String getBanktranid() {
        return this.banktranid;
    }

    public void setBanktranid(String banktranid) {
        this.banktranid = banktranid;
    }

    @Column(name = "RESPTYPE", length = 2)
    public String getResptype() {
        return this.resptype;
    }

    public void setResptype(String resptype) {
        this.resptype = resptype;
    }

    @Column(name = "RESPCODE", length = 10)
    public String getRespcode() {
        return this.respcode;
    }

    public void setRespcode(String respcode) {
        this.respcode = respcode;
    }

    @Column(name = "RESPMSG", length = 512)
    public String getRespmsg() {
        return this.respmsg;
    }

    public void setRespmsg(String respmsg) {
        this.respmsg = respmsg;
    }

    @Column(name = "TRANDATE", length = 8)
    public String getTrandate() {
        return this.trandate;
    }

    public void setTrandate(String trandate) {
        this.trandate = trandate;
    }

    @Column(name = "TRANTIME", length = 14)
    public String getTrantime() {
        return this.trantime;
    }

    public void setTrantime(String trantime) {
        this.trantime = trantime;
    }

    @Column(name = "RELATEDORDERNO", length = 16)
    public String getRelatedorderno() {
        return this.relatedorderno;
    }

    public void setRelatedorderno(String relatedorderno) {
        this.relatedorderno = relatedorderno;
    }

    @Column(name = "BUSICODE", length = 8)
    public String getBusicode() {
        return this.busicode;
    }

    public void setBusicode(String busicode) {
        this.busicode = busicode;
    }
    @Column(name = "SPLITFLAG", length = 1)
    public String getSplitflag() {
        return splitflag;
    }

    public void setSplitflag(String splitflag) {
        this.splitflag = splitflag;
    }
    @Column(name = "ACCSTATUS", length = 2)
    public String getAccstatus() {
        return accstatus;
    }

    public void setAccstatus(String accstatus) {
        this.accstatus = accstatus;
    }
    @Column(name = "ACCINFO", length = 128)
    public String getAccinfo() {
        return accinfo;
    }

    public void setAccinfo(String accinfo) {
        this.accinfo = accinfo;
    }
    @Column(name = "TRANSFERTYPE", length = 2)
    public String getTransfertype() {
        return transfertype;
    }

    public void setTransfertype(String transfertype) {
        this.transfertype = transfertype;
    }
    @Generated(GenerationTime.INSERT)
    @Column(name = "CREATETIME")
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Column(name = "MEMBERID", length = 15)
    public String getMemberid() {
        return memberid;
    }
    public void setMemberid(String memberid) {
        this.memberid = memberid;
    }
    @Column(name = "BUSITYPE", length = 4)
    public String getBusitype() {
        return busitype;
    }

    public void setBusitype(String busitype) {
        this.busitype = busitype;
    }
    @Column(name = "TXNFEE")
    public BigDecimal getTxnfee() {
        return txnfee;
    }
    public void setTxnfee(BigDecimal txnfee) {
        this.txnfee = txnfee;
    }
    @Column(name = "TXNSEQNO")
    public String getTxnseqno() {
        return txnseqno;
    }
    public void setTxnseqno(String txnseqno) {
        this.txnseqno = txnseqno;
    }
    public String getBankTranDataNo() {
        return bankTranDataNo;
    }
    public void setBankTranDataNo(String bankTranDataNo) {
        this.bankTranDataNo = bankTranDataNo;
    }
    
   
   
    
  

    
}
