// default package
// Generated 2016-3-11 13:50:27 by Hibernate Tools 4.0.0
package com.zlebank.zplatform.trade.model;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TBankTranBatch generated by hbm2java
 */
@Entity
@Table(name = "T_BANK_TRAN_BATCH")
public class TBankTranBatchModel implements java.io.Serializable {

	private long tid;
	private String bankTranBatchNo;
	private String bankTranChannelId;
	private Integer totalCount;
	private BigDecimal totalAmt;
	private Integer successCount;
	private BigDecimal successAmt;
	private Integer failCount;
	private BigDecimal failAmt;
	private String status;
	private Character openStatus;
	private String tranStatus;
	private Date applyTime;
	private Date defaultCloseTime;
	private Date latestCloseTime;
	private Date closeTime;
	private String closeEvent;
	private Long tranUser;
	private String remark;

	public TBankTranBatchModel() {
	}

	public TBankTranBatchModel(long tid) {
		this.tid = tid;
	}

	public TBankTranBatchModel(long tid, String bankTranBatchNo,
			String bankTranChannelId, Integer totalCount, BigDecimal totalAmt,
			Integer successCount, BigDecimal successAmt, Integer failCount,
			BigDecimal failAmt, String status, Character openStatus,
			String tranStatus, Date applyTime, Date defaultCloseTime,
			Date latestCloseTime, Date closeTime, String closeEvent,
			Long tranUser, String remark) {
		this.tid = tid;
		this.bankTranBatchNo = bankTranBatchNo;
		this.bankTranChannelId = bankTranChannelId;
		this.totalCount = totalCount;
		this.totalAmt = totalAmt;
		this.successCount = successCount;
		this.successAmt = successAmt;
		this.failCount = failCount;
		this.failAmt = failAmt;
		this.status = status;
		this.openStatus = openStatus;
		this.tranStatus = tranStatus;
		this.applyTime = applyTime;
		this.defaultCloseTime = defaultCloseTime;
		this.latestCloseTime = latestCloseTime;
		this.closeTime = closeTime;
		this.closeEvent = closeEvent;
		this.tranUser = tranUser;
		this.remark = remark;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BANK_TRAN_BATCH_NO", length = 16)
	public String getBankTranBatchNo() {
		return this.bankTranBatchNo;
	}

	public void setBankTranBatchNo(String bankTranBatchNo) {
		this.bankTranBatchNo = bankTranBatchNo;
	}

	@Column(name = "BANK_TRAN_CHANNEL_ID", length = 16)
	public String getBankTranChannelId() {
		return this.bankTranChannelId;
	}

	public void setBankTranChannelId(String bankTranChannelId) {
		this.bankTranChannelId = bankTranChannelId;
	}

	@Column(name = "TOTAL_COUNT", precision = 8, scale = 0)
	public Integer getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	@Column(name = "TOTAL_AMT", precision = 12)
	public BigDecimal getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(BigDecimal totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "SUCCESS_COUNT", precision = 8, scale = 0)
	public Integer getSuccessCount() {
		return this.successCount;
	}

	public void setSuccessCount(Integer successCount) {
		this.successCount = successCount;
	}

	@Column(name = "SUCCESS_AMT", precision = 12)
	public BigDecimal getSuccessAmt() {
		return this.successAmt;
	}

	public void setSuccessAmt(BigDecimal successAmt) {
		this.successAmt = successAmt;
	}

	@Column(name = "FAIL_COUNT", precision = 8, scale = 0)
	public Integer getFailCount() {
		return this.failCount;
	}

	public void setFailCount(Integer failCount) {
		this.failCount = failCount;
	}

	@Column(name = "FAIL_AMT", precision = 12)
	public BigDecimal getFailAmt() {
		return this.failAmt;
	}

	public void setFailAmt(BigDecimal failAmt) {
		this.failAmt = failAmt;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "OPEN_STATUS", length = 1)
	public Character getOpenStatus() {
		return this.openStatus;
	}

	public void setOpenStatus(Character openStatus) {
		this.openStatus = openStatus;
	}

	@Column(name = "TRAN_STATUS", length = 2)
	public String getTranStatus() {
		return this.tranStatus;
	}

	public void setTranStatus(String tranStatus) {
		this.tranStatus = tranStatus;
	}

	
	@Column(name = "APPLY_TIME", length = 7)
	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	
	@Column(name = "DEFAULT_CLOSE_TIME", length = 7)
	public Date getDefaultCloseTime() {
		return this.defaultCloseTime;
	}

	public void setDefaultCloseTime(Date defaultCloseTime) {
		this.defaultCloseTime = defaultCloseTime;
	}


	@Column(name = "LATEST_CLOSE_TIME", length = 7)
	public Date getLatestCloseTime() {
		return this.latestCloseTime;
	}

	public void setLatestCloseTime(Date latestCloseTime) {
		this.latestCloseTime = latestCloseTime;
	}

	
	@Column(name = "CLOSE_TIME", length = 7)
	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	@Column(name = "CLOSE_EVENT", length = 2)
	public String getCloseEvent() {
		return this.closeEvent;
	}

	public void setCloseEvent(String closeEvent) {
		this.closeEvent = closeEvent;
	}

	@Column(name = "TRAN_USER", precision = 10, scale = 0)
	public Long getTranUser() {
		return this.tranUser;
	}

	public void setTranUser(Long tranUser) {
		this.tranUser = tranUser;
	}

	@Column(name = "REMARK", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
