// default package
// Generated 2016-3-11 13:50:27 by Hibernate Tools 4.0.0
package com.zlebank.zplatform.trade.model;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TBankTranData generated by hbm2java
 */
@Entity
@Table(name = "T_BANK_TRAN_DATA")
public class TBankTranDataModel implements java.io.Serializable {

	private long tid;
	private String bankTranDataSeqNo;
	private long bankTranBatchId;
	private String tranDataId;
	private BigDecimal tranAmt;
	private String accNo;
	private String accName;
	private String accBankNo;
	private String accBankName;
	private String status;
	private String resCode;
	private String resInfo;
	private Date applyTime;
	private String accType;
	private String transferType;
	private String resType;

	public TBankTranDataModel() {
	}

	public TBankTranDataModel(long tid, String bankTranDataSeqNo,
			long bankTranBatchId, String tranDataId, BigDecimal tranAmt,
			String accNo, String status) {
		this.tid = tid;
		this.bankTranDataSeqNo = bankTranDataSeqNo;
		this.bankTranBatchId = bankTranBatchId;
		this.tranDataId = tranDataId;
		this.tranAmt = tranAmt;
		this.accNo = accNo;
		this.status = status;
	}

	public TBankTranDataModel(long tid, String bankTranDataSeqNo,
			long bankTranBatchId, String tranDataId, BigDecimal tranAmt,
			String accNo, String accName, String accBankNo, String accBankName,
			String status, String resCode, String resInfo, Date applyTime,
			String accType, String transferType, String resType) {
		this.tid = tid;
		this.bankTranDataSeqNo = bankTranDataSeqNo;
		this.bankTranBatchId = bankTranBatchId;
		this.tranDataId = tranDataId;
		this.tranAmt = tranAmt;
		this.accNo = accNo;
		this.accName = accName;
		this.accBankNo = accBankNo;
		this.accBankName = accBankName;
		this.status = status;
		this.resCode = resCode;
		this.resInfo = resInfo;
		this.applyTime = applyTime;
		this.accType = accType;
		this.transferType = transferType;
		this.resType = resType;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BANK_TRAN_DATA_SEQ_NO", nullable = false, length = 24)
	public String getBankTranDataSeqNo() {
		return this.bankTranDataSeqNo;
	}

	public void setBankTranDataSeqNo(String bankTranDataSeqNo) {
		this.bankTranDataSeqNo = bankTranDataSeqNo;
	}

	@Column(name = "BANK_TRAN_BATCH_ID", nullable = false, precision = 10, scale = 0)
	public long getBankTranBatchId() {
		return this.bankTranBatchId;
	}

	public void setBankTranBatchId(long bankTranBatchId) {
		this.bankTranBatchId = bankTranBatchId;
	}

	@Column(name = "TRAN_DATA_ID", nullable = false, length = 16)
	public String getTranDataId() {
		return this.tranDataId;
	}

	public void setTranDataId(String tranDataId) {
		this.tranDataId = tranDataId;
	}

	@Column(name = "TRAN_AMT", nullable = false, precision = 12)
	public BigDecimal getTranAmt() {
		return this.tranAmt;
	}

	public void setTranAmt(BigDecimal tranAmt) {
		this.tranAmt = tranAmt;
	}

	@Column(name = "ACC_NO", nullable = false, length = 32)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "ACC_NAME", length = 32)
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	@Column(name = "ACC_BANK_NO", length = 12)
	public String getAccBankNo() {
		return this.accBankNo;
	}

	public void setAccBankNo(String accBankNo) {
		this.accBankNo = accBankNo;
	}

	@Column(name = "ACC_BANK_NAME", length = 64)
	public String getAccBankName() {
		return this.accBankName;
	}

	public void setAccBankName(String accBankName) {
		this.accBankName = accBankName;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "RES_CODE", length = 8)
	public String getResCode() {
		return this.resCode;
	}

	public void setResCode(String resCode) {
		this.resCode = resCode;
	}

	@Column(name = "RES_INFO", length = 128)
	public String getResInfo() {
		return this.resInfo;
	}

	public void setResInfo(String resInfo) {
		this.resInfo = resInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPLY_TIME", length = 7)
	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	@Column(name = "ACC_TYPE", length = 2)
	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	@Column(name = "TRANSFER_TYPE", length = 2)
	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	@Column(name = "RES_TYPE", length = 2)
	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

}
