// default package
// Generated 2016-3-11 13:50:27 by Hibernate Tools 4.0.0
package com.zlebank.zplatform.trade.model;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTranData generated by hbm2java
 */
@Entity
@Table(name = "T_TRAN_DATA")
public class TTranDataModel implements java.io.Serializable {

	private long tid;
	private String tranDataSeqNo;
	private Long tranBatchId;
	private Character accType;
	private String accNo;
	private String accName;
	private String bankNo;
	private String bankName;
	private BigDecimal tranAmt;
	private String remark;
	private String status;
	private Date applyTime;
	private Date approveTime;
	private Long approveUser;
	private BigDecimal tranFee;
	private String bankTranDataId;
	private String memberId;
	private String txnseqno;
	private String busiType;

	public TTranDataModel() {
	}

	public TTranDataModel(long tid) {
		this.tid = tid;
	}

	public TTranDataModel(long tid, String tranDataSeqNo, Long tranBatchId,
			Character accType, String accNo, String accName, String bankNo,
			String bankName, BigDecimal tranAmt, String remark, String status,
			Date applyTime, Date approveTime, Long approveUser,
			BigDecimal tranFee, String bankTranDataId, String memberId,
			String txnseqno, String busiType) {
		this.tid = tid;
		this.tranDataSeqNo = tranDataSeqNo;
		this.tranBatchId = tranBatchId;
		this.accType = accType;
		this.accNo = accNo;
		this.accName = accName;
		this.bankNo = bankNo;
		this.bankName = bankName;
		this.tranAmt = tranAmt;
		this.remark = remark;
		this.status = status;
		this.applyTime = applyTime;
		this.approveTime = approveTime;
		this.approveUser = approveUser;
		this.tranFee = tranFee;
		this.bankTranDataId = bankTranDataId;
		this.memberId = memberId;
		this.txnseqno = txnseqno;
		this.busiType = busiType;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "TRAN_DATA_SEQ_NO", length = 24)
	public String getTranDataSeqNo() {
		return this.tranDataSeqNo;
	}

	public void setTranDataSeqNo(String tranDataSeqNo) {
		this.tranDataSeqNo = tranDataSeqNo;
	}

	@Column(name = "TRAN_BATCH_ID", precision = 12, scale = 0)
	public Long getTranBatchId() {
		return this.tranBatchId;
	}

	public void setTranBatchId(Long tranBatchId) {
		this.tranBatchId = tranBatchId;
	}

	@Column(name = "ACC_TYPE", length = 1)
	public Character getAccType() {
		return this.accType;
	}

	public void setAccType(Character accType) {
		this.accType = accType;
	}

	@Column(name = "ACC_NO", length = 32)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "ACC_NAME", length = 32)
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	@Column(name = "BANK_NO", length = 12)
	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	@Column(name = "BANK_NAME", length = 64)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "TRAN_AMT", precision = 12)
	public BigDecimal getTranAmt() {
		return this.tranAmt;
	}

	public void setTranAmt(BigDecimal tranAmt) {
		this.tranAmt = tranAmt;
	}

	@Column(name = "REMARK", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPLY_TIME", length = 7)
	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPROVE_TIME", length = 7)
	public Date getApproveTime() {
		return this.approveTime;
	}

	public void setApproveTime(Date approveTime) {
		this.approveTime = approveTime;
	}

	@Column(name = "APPROVE_USER", precision = 10, scale = 0)
	public Long getApproveUser() {
		return this.approveUser;
	}

	public void setApproveUser(Long approveUser) {
		this.approveUser = approveUser;
	}

	@Column(name = "TRAN_FEE", precision = 12)
	public BigDecimal getTranFee() {
		return this.tranFee;
	}

	public void setTranFee(BigDecimal tranFee) {
		this.tranFee = tranFee;
	}

	@Column(name = "BANK_TRAN_DATA_ID", length = 16)
	public String getBankTranDataId() {
		return this.bankTranDataId;
	}

	public void setBankTranDataId(String bankTranDataId) {
		this.bankTranDataId = bankTranDataId;
	}

	@Column(name = "MEMBER_ID", length = 15)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "TXNSEQNO", length = 16)
	public String getTxnseqno() {
		return this.txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	@Column(name = "BUSI_TYPE", length = 2)
	public String getBusiType() {
		return this.busiType;
	}

	public void setBusiType(String busiType) {
		this.busiType = busiType;
	}

}
