package com.zlebank.zplatform.trade.model;
// Generated 2015-11-9 9:45:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTxnsNotifyTask generated by hbm2java
 */
@Entity
@Table(name = "T_TXNS_NOTIFY_TASK")
public class TxnsNotifyTaskModel implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1112312515568183790L;
    private long id;
    private String memberId;
    private String txnseqno;
    private Integer sendTimes;
    private Integer maxSendTimes;
    private String data;
    private String sendStatus;
    private String httpRescode;
    private String notifyUrl;
    private String taskType;
    public TxnsNotifyTaskModel() {
    }

    public TxnsNotifyTaskModel(long id) {
        this.id = id;
    }
    public TxnsNotifyTaskModel(long id, String memberId, String txnseqno,
            Integer sendTimes, Integer maxSendTimes, String data,
            String sendStatus, String httpRescode, String notifyUrl) {
        this.id = id;
        this.memberId = memberId;
        this.txnseqno = txnseqno;
        this.sendTimes = sendTimes;
        this.maxSendTimes = maxSendTimes;
        this.data = data;
        this.sendStatus = sendStatus;
        this.httpRescode = httpRescode;
        this.notifyUrl = notifyUrl;
    }
    public TxnsNotifyTaskModel(String memberId, String txnseqno,
            int sendTimes, int maxSendTimes, String data,
            String sendStatus, String httpRescode, String notifyUrl,String taskType) {
        this.id =1L;
        this.memberId = memberId;
        this.txnseqno = txnseqno;
        this.sendTimes = sendTimes;
        this.maxSendTimes = maxSendTimes;
        this.data = data;
        this.sendStatus = sendStatus;
        this.httpRescode = httpRescode;
        this.notifyUrl = notifyUrl;
        this.taskType = taskType;
    }
    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "MEMBER_ID", length = 15)
    public String getMemberId() {
        return this.memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    @Column(name = "TXNSEQNO", length = 32)
    public String getTxnseqno() {
        return this.txnseqno;
    }

    public void setTxnseqno(String txnseqno) {
        this.txnseqno = txnseqno;
    }

    @Column(name = "SEND_TIMES", precision = 3, scale = 0)
    public Integer getSendTimes() {
        return this.sendTimes;
    }

    public void setSendTimes(Integer sendTimes) {
        this.sendTimes = sendTimes;
    }

    @Column(name = "MAX_SEND_TIMES", precision = 3, scale = 0)
    public Integer getMaxSendTimes() {
        return this.maxSendTimes;
    }

    public void setMaxSendTimes(Integer maxSendTimes) {
        this.maxSendTimes = maxSendTimes;
    }

    @Column(name = "DATA", length = 2048)
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    @Column(name = "SEND_STATUS", length = 2)
    public String getSendStatus() {
        return this.sendStatus;
    }

    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus;
    }

    @Column(name = "HTTP_RESCODE", length = 4)
    public String getHttpRescode() {
        return this.httpRescode;
    }

    public void setHttpRescode(String httpRescode) {
        this.httpRescode = httpRescode;
    }

    @Column(name = "NOTIFY_URL", length = 256)
    public String getNotifyUrl() {
        return this.notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * @return the taskType 
     */
    @Column(name = "TASK_TYPE", length = 1)
    public String getTaskType() {
        return taskType;
    }

    /**
     * @param taskType the taskType to set
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

}
