package com.zlebank.zplatform.trade.model;
// Generated 2015-10-26 14:20:55 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TWithdrawBatch generated by hbm2java
 */
@Entity
@Table(name = "T_WITHDRAW_BATCH")
public class WithdrawBatchModel implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = -4970709929346361569L;
    private long id;
    private String batchno;
    private Long sumitem;
    private Long sumamount;
    private Long succitem;
    private Long succamount;
    private Long failitem;
    private Long failamount;
    private String status;
    private String notes;
    private String remarks;

    public WithdrawBatchModel() {
    }

    public WithdrawBatchModel(long id) {
        this.id = id;
    }
    public WithdrawBatchModel(long id, String batchno, Long sumitem,
            Long sumamount, Long succitem, Long succamount, Long failitem,
            Long failamount, String status, String notes, String remarks) {
        this.id = id;
        this.batchno = batchno;
        this.sumitem = sumitem;
        this.sumamount = sumamount;
        this.succitem = succitem;
        this.succamount = succamount;
        this.failitem = failitem;
        this.failamount = failamount;
        this.status = status;
        this.notes = notes;
        this.remarks = remarks;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "BATCHNO", length = 32)
    public String getBatchno() {
        return this.batchno;
    }

    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    @Column(name = "SUMITEM", precision = 12, scale = 0)
    public Long getSumitem() {
        return this.sumitem;
    }

    public void setSumitem(Long sumitem) {
        this.sumitem = sumitem;
    }

    @Column(name = "SUMAMOUNT", precision = 12, scale = 0)
    public Long getSumamount() {
        return this.sumamount;
    }

    public void setSumamount(Long sumamount) {
        this.sumamount = sumamount;
    }

    @Column(name = "SUCCITEM", precision = 12, scale = 0)
    public Long getSuccitem() {
        return this.succitem;
    }

    public void setSuccitem(Long succitem) {
        this.succitem = succitem;
    }

    @Column(name = "SUCCAMOUNT", precision = 12, scale = 0)
    public Long getSuccamount() {
        return this.succamount;
    }

    public void setSuccamount(Long succamount) {
        this.succamount = succamount;
    }

    @Column(name = "FAILITEM", precision = 12, scale = 0)
    public Long getFailitem() {
        return this.failitem;
    }

    public void setFailitem(Long failitem) {
        this.failitem = failitem;
    }

    @Column(name = "FAILAMOUNT", precision = 12, scale = 0)
    public Long getFailamount() {
        return this.failamount;
    }

    public void setFailamount(Long failamount) {
        this.failamount = failamount;
    }

    @Column(name = "STATUS", length = 2)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "NOTES", length = 256)
    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Column(name = "REMARKS", length = 256)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
